
package danielreyes_examen1p2;

import java.util.ArrayList;
import java.util.Scanner;


/**
 *
 * @author alema
 */
public class GUI extends javax.swing.JFrame {

    private ArrayList<Pc> listapc = new ArrayList();
    public GUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupoboolean = new javax.swing.ButtonGroup();
        JFrameCrud = new javax.swing.JFrame();
        PanelCRUD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonAgregar = new javax.swing.JButton();
        ButtonListar = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        ButtonVolver = new javax.swing.JButton();
        JFrameAgregar = new javax.swing.JFrame();
        PanelAgregar = new javax.swing.JPanel();
        Buttonagregarescritorio = new javax.swing.JButton();
        Buttonagregarlaptop = new javax.swing.JButton();
        JFrameEscritorio = new javax.swing.JFrame();
        PanelEscritorio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldhostname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldmask = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldip = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldram = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldalmacen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldtipo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        buttonsi = new javax.swing.JRadioButton();
        buttonno = new javax.swing.JRadioButton();
        Guardarescritorio = new javax.swing.JButton();
        JFrameLaptop = new javax.swing.JFrame();
        PanelLaptop = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldhostname1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fieldmask1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fieldip1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fieldmarca = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fielddefpantalla = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        buttonsi1 = new javax.swing.JRadioButton();
        buttonno1 = new javax.swing.JRadioButton();
        Guardarlaptop = new javax.swing.JButton();
        JFrameListar = new javax.swing.JFrame();
        PanelListar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CajaLista = new javax.swing.JTextPane();
        JFrameEliminar = new javax.swing.JFrame();
        PanelEliminar = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Fieldindiceelminar = new javax.swing.JTextField();
        ButtonEliminarCRUD = new javax.swing.JButton();
        PanelBase = new javax.swing.JPanel();
        textox = new javax.swing.JLabel();
        ButtonEntrarCRUD = new javax.swing.JButton();
        ButtonIngresarPc = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        PanelCRUD.setBackground(new java.awt.Color(204, 204, 204));
        PanelCRUD.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel1.setText("CRUD");

        ButtonAgregar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAgregar.setText("Agregar");
        ButtonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAgregarMouseClicked(evt);
            }
        });

        ButtonListar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonListar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonListar.setText("Listar");
        ButtonListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonListarMouseClicked(evt);
            }
        });

        ButtonEliminar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEliminarMouseClicked(evt);
            }
        });

        ButtonVolver.setText("Volver");
        ButtonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelCRUDLayout = new javax.swing.GroupLayout(PanelCRUD);
        PanelCRUD.setLayout(PanelCRUDLayout);
        PanelCRUDLayout.setHorizontalGroup(
            PanelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCRUDLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(PanelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        PanelCRUDLayout.setVerticalGroup(
            PanelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCRUDLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(ButtonAgregar)
                .addGap(51, 51, 51)
                .addComponent(ButtonListar)
                .addGap(60, 60, 60)
                .addComponent(ButtonEliminar)
                .addGap(54, 54, 54)
                .addComponent(ButtonVolver)
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout JFrameCrudLayout = new javax.swing.GroupLayout(JFrameCrud.getContentPane());
        JFrameCrud.getContentPane().setLayout(JFrameCrudLayout);
        JFrameCrudLayout.setHorizontalGroup(
            JFrameCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(JFrameCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameCrudLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JFrameCrudLayout.setVerticalGroup(
            JFrameCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(JFrameCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameCrudLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelAgregar.setBackground(new java.awt.Color(204, 204, 204));

        Buttonagregarescritorio.setText("Agregar PC de Escritorio");
        Buttonagregarescritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonagregarescritorioActionPerformed(evt);
            }
        });

        Buttonagregarlaptop.setText("Agregar Laptop");
        Buttonagregarlaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonagregarlaptopMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelAgregarLayout = new javax.swing.GroupLayout(PanelAgregar);
        PanelAgregar.setLayout(PanelAgregarLayout);
        PanelAgregarLayout.setHorizontalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buttonagregarescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buttonagregarlaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );
        PanelAgregarLayout.setVerticalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(Buttonagregarescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(Buttonagregarlaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JFrameAgregarLayout = new javax.swing.GroupLayout(JFrameAgregar.getContentPane());
        JFrameAgregar.getContentPane().setLayout(JFrameAgregarLayout);
        JFrameAgregarLayout.setHorizontalGroup(
            JFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(JFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameAgregarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JFrameAgregarLayout.setVerticalGroup(
            JFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(JFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameAgregarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelEscritorio.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel2.setText("Agregar Escritorio");

        jLabel3.setText("Host name");

        jLabel4.setText("Mascara de Red");

        jLabel5.setText("Capacidad de RAM");

        jLabel6.setText("Dirreción IP");

        jLabel7.setText("Capacidad de Almacenamiento");

        jLabel8.setText("Tipo de almacen");

        jLabel9.setText("Tarjeta Gráfica");

        buttonsi.setText("Si");
        buttonsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsiMouseClicked(evt);
            }
        });

        buttonno.setText("No");
        buttonno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonnoActionPerformed(evt);
            }
        });

        Guardarescritorio.setBackground(new java.awt.Color(153, 255, 153));
        Guardarescritorio.setText("Guardar");
        Guardarescritorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarescritorioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelEscritorioLayout = new javax.swing.GroupLayout(PanelEscritorio);
        PanelEscritorio.setLayout(PanelEscritorioLayout);
        PanelEscritorioLayout.setHorizontalGroup(
            PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEscritorioLayout.createSequentialGroup()
                .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEscritorioLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEscritorioLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEscritorioLayout.createSequentialGroup()
                                .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldhostname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldmask, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonno, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonsi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelEscritorioLayout.createSequentialGroup()
                                .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldip, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldalmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelEscritorioLayout.createSequentialGroup()
                                .addComponent(fieldram, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Guardarescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))))
                .addGap(37, 37, 37))
        );
        PanelEscritorioLayout.setVerticalGroup(
            PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEscritorioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldhostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldmask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonsi))
                .addGap(16, 16, 16)
                .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(buttonno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guardarescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldalmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JFrameEscritorioLayout = new javax.swing.GroupLayout(JFrameEscritorio.getContentPane());
        JFrameEscritorio.getContentPane().setLayout(JFrameEscritorioLayout);
        JFrameEscritorioLayout.setHorizontalGroup(
            JFrameEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(JFrameEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameEscritorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JFrameEscritorioLayout.setVerticalGroup(
            JFrameEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(JFrameEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameEscritorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelLaptop.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel10.setText("Agregar Laptop");

        jLabel11.setText("Host name");

        jLabel12.setText("Mascara de Red");

        jLabel13.setText("Marca");

        jLabel14.setText("Dirreción IP");

        jLabel15.setText("Definicion de pantalla");

        jLabel17.setText("RGB");

        buttonsi1.setText("Si");
        buttonsi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsi1MouseClicked(evt);
            }
        });

        buttonno1.setText("No");
        buttonno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonno1ActionPerformed(evt);
            }
        });

        Guardarlaptop.setBackground(new java.awt.Color(153, 255, 153));
        Guardarlaptop.setText("Guardar");
        Guardarlaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarlaptopMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelLaptopLayout = new javax.swing.GroupLayout(PanelLaptop);
        PanelLaptop.setLayout(PanelLaptopLayout);
        PanelLaptopLayout.setHorizontalGroup(
            PanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLaptopLayout.createSequentialGroup()
                .addGroup(PanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLaptopLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLaptopLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(PanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLaptopLayout.createSequentialGroup()
                                .addGroup(PanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldhostname1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldmask1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(PanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonno1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelLaptopLayout.createSequentialGroup()
                                .addGroup(PanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldip1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fielddefpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelLaptopLayout.createSequentialGroup()
                                .addComponent(fieldmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Guardarlaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))))
                .addGap(37, 37, 37))
        );
        PanelLaptopLayout.setVerticalGroup(
            PanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLaptopLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldhostname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(PanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldmask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonsi1))
                .addGap(16, 16, 16)
                .addGroup(PanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(buttonno1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guardarlaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fielddefpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JFrameLaptopLayout = new javax.swing.GroupLayout(JFrameLaptop.getContentPane());
        JFrameLaptop.getContentPane().setLayout(JFrameLaptopLayout);
        JFrameLaptopLayout.setHorizontalGroup(
            JFrameLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(JFrameLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameLaptopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JFrameLaptopLayout.setVerticalGroup(
            JFrameLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(JFrameLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameLaptopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelListar.setBackground(new java.awt.Color(0, 0, 0));

        jLabel16.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Listar");

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(CajaLista);

        javax.swing.GroupLayout PanelListarLayout = new javax.swing.GroupLayout(PanelListar);
        PanelListar.setLayout(PanelListarLayout);
        PanelListarLayout.setHorizontalGroup(
            PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListarLayout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListarLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListarLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        PanelListarLayout.setVerticalGroup(
            PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JFrameListarLayout = new javax.swing.GroupLayout(JFrameListar.getContentPane());
        JFrameListar.getContentPane().setLayout(JFrameListarLayout);
        JFrameListarLayout.setHorizontalGroup(
            JFrameListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(JFrameListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameListarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JFrameListarLayout.setVerticalGroup(
            JFrameListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(JFrameListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameListarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelEliminar.setBackground(new java.awt.Color(0, 0, 0));

        jLabel18.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Eliminar");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ingrese un índice a eliminar de la lista de Pcs");

        ButtonEliminarCRUD.setBackground(new java.awt.Color(255, 204, 204));
        ButtonEliminarCRUD.setForeground(new java.awt.Color(255, 51, 51));
        ButtonEliminarCRUD.setText("Eliminar");
        ButtonEliminarCRUD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEliminarCRUDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelEliminarLayout = new javax.swing.GroupLayout(PanelEliminar);
        PanelEliminar.setLayout(PanelEliminarLayout);
        PanelEliminarLayout.setHorizontalGroup(
            PanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelEliminarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Fieldindiceelminar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEliminarLayout.createSequentialGroup()
                        .addComponent(ButtonEliminarCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        PanelEliminarLayout.setVerticalGroup(
            PanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEliminarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(Fieldindiceelminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(ButtonEliminarCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout JFrameEliminarLayout = new javax.swing.GroupLayout(JFrameEliminar.getContentPane());
        JFrameEliminar.getContentPane().setLayout(JFrameEliminarLayout);
        JFrameEliminarLayout.setHorizontalGroup(
            JFrameEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(JFrameEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameEliminarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JFrameEliminarLayout.setVerticalGroup(
            JFrameEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(JFrameEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFrameEliminarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        PanelBase.setBackground(new java.awt.Color(204, 204, 204));

        textox.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        textox.setText("Examen 1-P2 Daniel Reyes");

        ButtonEntrarCRUD.setBackground(new java.awt.Color(0, 0, 0));
        ButtonEntrarCRUD.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEntrarCRUD.setText("CRUD PC");
        ButtonEntrarCRUD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEntrarCRUDMouseClicked(evt);
            }
        });

        ButtonIngresarPc.setBackground(new java.awt.Color(0, 0, 0));
        ButtonIngresarPc.setForeground(new java.awt.Color(255, 255, 255));
        ButtonIngresarPc.setText("Ingresar PC");
        ButtonIngresarPc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonIngresarPcMouseClicked(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBaseLayout = new javax.swing.GroupLayout(PanelBase);
        PanelBase.setLayout(PanelBaseLayout);
        PanelBaseLayout.setHorizontalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                        .addComponent(textox, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonIngresarPc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonEntrarCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112))))
        );
        PanelBaseLayout.setVerticalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(textox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(ButtonEntrarCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(ButtonIngresarPc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton3MouseClicked

    private void ButtonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVolverMouseClicked
        PanelCRUD.setVisible(false);
        PanelBase.setVisible(true);
        JFrameCrud.setVisible(false);
        
    }//GEN-LAST:event_ButtonVolverMouseClicked

    private void ButtonEntrarCRUDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEntrarCRUDMouseClicked
        PanelCRUD.setVisible(true);
        PanelBase.setVisible(false);
        JFrameCrud.setVisible(true);
        JFrameCrud.setSize(510, 520);
        
    }//GEN-LAST:event_ButtonEntrarCRUDMouseClicked

    private void ButtonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAgregarMouseClicked
        PanelCRUD.setVisible(false);
        PanelAgregar.setVisible(true);
        JFrameCrud.setVisible(false);
        JFrameAgregar.setVisible(true);
        JFrameAgregar.setSize(510, 520);
    }//GEN-LAST:event_ButtonAgregarMouseClicked

    private void buttonsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsiMouseClicked
        Grupoboolean.add(buttonsi);
        
    }//GEN-LAST:event_buttonsiMouseClicked

    private void buttonnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonnoActionPerformed
        Grupoboolean.add(buttonno);
    }//GEN-LAST:event_buttonnoActionPerformed

    private void ButtonagregarescritorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonagregarescritorioActionPerformed
        JFrameAgregar.setVisible(false);
        JFrameEscritorio.setVisible(true);
        PanelEscritorio.setVisible(true);
        JFrameEscritorio.setSize(510,520);
    }//GEN-LAST:event_ButtonagregarescritorioActionPerformed

    private void GuardarescritorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarescritorioMouseClicked
        boolean tarjetagraf;
        if(Grupoboolean.getSelection()== buttonsi){
            tarjetagraf = true;
        }else{
            tarjetagraf= false;
        }
        try {
                 listapc.add(new Escritorio(Integer.parseInt(fieldram.getText()), Integer.parseInt(fieldalmacen.getText()), fieldtipo.getText(), tarjetagraf, fieldip.getText(), fieldmask.getText(), fieldhostname.getText()));
        } catch (Exception e) {
        }
        fieldip.setText("");
        fieldmask.setText("");
        fieldhostname.setText("");
        fieldram.setText("");
        fieldalmacen.setText("");
        fieldtipo.setText("");
        
        JFrameEscritorio.setVisible(false);
        PanelEscritorio.setVisible(false);
        JFrameCrud.setVisible(true);
        JFrameCrud.setSize(510, 520);
        PanelCRUD.setVisible(true);
    }//GEN-LAST:event_GuardarescritorioMouseClicked

    private void ButtonagregarlaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonagregarlaptopMouseClicked
        JFrameAgregar.setVisible(false);
        JFrameLaptop.setVisible(true);
        PanelLaptop.setVisible(true);
        JFrameLaptop.setSize(510,520);
    }//GEN-LAST:event_ButtonagregarlaptopMouseClicked

    private void buttonsi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsi1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonsi1MouseClicked

    private void buttonno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonno1ActionPerformed

    private void GuardarlaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarlaptopMouseClicked
        boolean tarjetagraf2;
        if(Grupoboolean.getSelection()== buttonsi){
            tarjetagraf2 = true;
        }else{
            tarjetagraf2= false;
        }
        try{
        listapc.add(new Laptops(fieldmarca.getText(), fielddefpantalla.getText(), tarjetagraf2, fieldip1.getText(), fieldmask1.getText(), fieldhostname1.getText()));
        }catch(Exception e){
            
        }
        fieldmarca.setText("");
        fielddefpantalla.setText("");
        fieldip1.setText("");
        fieldmask1.setText("");
        fieldhostname1.setText("");
        
        JFrameLaptop.setVisible(false);
        PanelLaptop.setVisible(false);
        JFrameCrud.setVisible(true);
        JFrameCrud.setSize(510, 520);
        PanelCRUD.setVisible(true);
    }//GEN-LAST:event_GuardarlaptopMouseClicked

    private void ButtonListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonListarMouseClicked
        PanelCRUD.setVisible(false);
        PanelListar.setVisible(true);
        JFrameCrud.setVisible(false);
        JFrameListar.setVisible(true);
        JFrameListar.setSize(510, 520);
        
        CajaLista.setText(listapc.toString());
        
    }//GEN-LAST:event_ButtonListarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        PanelCRUD.setVisible(true);
        PanelListar.setVisible(false);
        JFrameCrud.setVisible(true);
        JFrameListar.setVisible(false);
        JFrameCrud.setSize(510, 520);
    }//GEN-LAST:event_jButton1MouseClicked

    private void ButtonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEliminarMouseClicked
        PanelCRUD.setVisible(false);
        PanelEliminar.setVisible(true);
        JFrameCrud.setVisible(false);
        JFrameEliminar.setVisible(true);
        JFrameEliminar.setSize(510, 520);
        
        
        
    }//GEN-LAST:event_ButtonEliminarMouseClicked

    private void ButtonEliminarCRUDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEliminarCRUDMouseClicked
        int temp;
        try {
            temp = Integer.parseInt(Fieldindiceelminar.getText());
            listapc.remove(temp);
        } catch (Exception e) {
        }
        PanelEliminar.setVisible(false);
        PanelCRUD.setVisible(true);
        JFrameEliminar.setVisible(false);
        JFrameCrud.setVisible(true);
        JFrameCrud.setSize(510, 520);
        Fieldindiceelminar.setText("");
        
    }//GEN-LAST:event_ButtonEliminarCRUDMouseClicked

    private void ButtonIngresarPcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonIngresarPcMouseClicked
        Scanner leer = new Scanner(System.in);
        boolean b = false;
        PanelBase.setVisible(false);
        System.out.println("PC a ingresar a la consola");
        for (Pc pc : listapc) {
            System.out.println(""+listapc.indexOf(pc)+"- "+ pc);
        }
        System.out.println("Ingrese el indice de su PC: ");
        int indice = leer.nextInt();
        do{
            if(listapc.size() > indice && indice >= 0){
                b = true;
            }else{
                b = false;
                System.out.println("Esa PC no existe");
                System.out.println("Ingrese el indice de su PC: ");
                indice = leer.nextInt();
            }
        
        }while(b != true);
        do{
            int verifier=0;
            b= false;
            System.out.print(listapc.get(indice).getHostname() + "#");
            String comando = leer.next();
            
            System.out.println("");
            System.out.println("Pinging to "+listapc.get(indice).getDireccionIp()+" with 32 bits of data: ");
            
            if(comando.equals("show")){
                System.out.println("Ip: "+ listapc.get(indice).getDireccionIp()+"\nMask: "+ listapc.get(indice).getMascaraRed());
                b = false;
            }else if(comando.equals("exit")){
                System.out.println("Saliendo de la consola, devolviendo al GUI...");
                b = true;
            }else{
                String nuevoip="";
                for (int i = 0; i < comando.length(); i++) {
                    if(i >= 5){
                        nuevoip+= comando.charAt(i);
                    }
                }
                for (Pc p : listapc) {
                    if(p.getDireccionIp().equals(nuevoip)){
                        //System.out.println("ping exitoso");
                        verifier++;
                        
                        String bi="";
                        bi = listapc.get(indice).getDireccionIp().split("\\.")[3];
                        // binario ip
                        int ipbinariotemp =Integer.parseInt(bi);
                        int modulo;
                        String ipbinario="";
                        while(ipbinariotemp>0){
                            modulo = ipbinariotemp%2;
                            ipbinario = modulo+ ipbinario;
                            ipbinariotemp = ipbinariotemp/2;
                        }
                        String bm ="";
                        bm = listapc.get(indice).getMascaraRed().split("\\.")[3];
                        //binario mask
                        int maskbinariotemp = Integer.parseInt(bm);
                        int modulo2;
                        String maskbinario="";
                        while(maskbinariotemp>0){
                            modulo2 = maskbinariotemp%2;
                            maskbinario = modulo2+maskbinario;
                            maskbinariotemp= maskbinariotemp/2;
                        }
                        String bi2="";
                        bi2 = p.getDireccionIp().split("\\.")[3];
                        //binario ip 2
                        int ipbinariotemp2 = Integer.parseInt(bi2);
                        int modulo3;
                        String ipbinario2="";
                        while(ipbinariotemp2>0){
                            modulo3 = ipbinariotemp2%2;
                            ipbinario2 = modulo3+ ipbinario2;
                            ipbinariotemp2 = ipbinariotemp2/2;
                        }
                        //comprobar
                        int contaunos=0;
                        String ip1="";
                        String ip2="";
                        for (int i = 0; i < maskbinario.length(); i++) {
                            if(maskbinario.charAt(i)== '1'){
                                contaunos++;
                            }else{
                                break;
                            }
                        }
                        for (int i = 0; i < contaunos; i++) {
                            ip1 += ipbinario.charAt(i);
                        }
                        for (int i = 0; i < contaunos; i++) {
                            ip2 += ipbinario2.charAt(i);
                        }
//                        System.out.println(ipbinario);
//                        System.out.println(ipbinario2);
//                        System.out.println(maskbinario);
//                        System.out.println(ip1);
//                        System.out.println(ip2);
                        if(ip1.equals(ip2)){
                            for (int i = 0; i < 4; i++) {
                                System.out.println("Reply from "+ p.getDireccionIp() +": "+ "Ping exitoso");
                            }
                        }else{
                            for (int i = 0; i < 4; i++) {
                                System.out.println("Reply from "+ p.getDireccionIp()+": "+ " Destination host unreachable");
                            }
                        }
                    }
                    
                }
                if(verifier == 0){
                    for (int i = 0; i < 4; i++) {
                            System.out.println("Request timed out");
                        }
                }
            }
                
            
        
        }while(b !=true);
        PanelBase.setVisible(true);
        
    }//GEN-LAST:event_ButtonIngresarPcMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgregar;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonEliminarCRUD;
    private javax.swing.JButton ButtonEntrarCRUD;
    private javax.swing.JButton ButtonIngresarPc;
    private javax.swing.JButton ButtonListar;
    private javax.swing.JButton ButtonVolver;
    private javax.swing.JButton Buttonagregarescritorio;
    private javax.swing.JButton Buttonagregarlaptop;
    private javax.swing.JTextPane CajaLista;
    private javax.swing.JTextField Fieldindiceelminar;
    private javax.swing.ButtonGroup Grupoboolean;
    private javax.swing.JButton Guardarescritorio;
    private javax.swing.JButton Guardarlaptop;
    private javax.swing.JFrame JFrameAgregar;
    private javax.swing.JFrame JFrameCrud;
    private javax.swing.JFrame JFrameEliminar;
    private javax.swing.JFrame JFrameEscritorio;
    private javax.swing.JFrame JFrameLaptop;
    private javax.swing.JFrame JFrameListar;
    private javax.swing.JPanel PanelAgregar;
    private javax.swing.JPanel PanelBase;
    private javax.swing.JPanel PanelCRUD;
    private javax.swing.JPanel PanelEliminar;
    private javax.swing.JPanel PanelEscritorio;
    private javax.swing.JPanel PanelLaptop;
    private javax.swing.JPanel PanelListar;
    private javax.swing.JRadioButton buttonno;
    private javax.swing.JRadioButton buttonno1;
    private javax.swing.JRadioButton buttonsi;
    private javax.swing.JRadioButton buttonsi1;
    private javax.swing.JTextField fieldalmacen;
    private javax.swing.JTextField fielddefpantalla;
    private javax.swing.JTextField fieldhostname;
    private javax.swing.JTextField fieldhostname1;
    private javax.swing.JTextField fieldip;
    private javax.swing.JTextField fieldip1;
    private javax.swing.JTextField fieldmarca;
    private javax.swing.JTextField fieldmask;
    private javax.swing.JTextField fieldmask1;
    private javax.swing.JTextField fieldram;
    private javax.swing.JTextField fieldtipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textox;
    // End of variables declaration//GEN-END:variables
}
